### ISSUE TITLE
点击确定取消按钮，直接崩溃掉了

### ISSUE THREAD

**Issue by jinwong001** [niuxiaowei/DialogFragmentUse#3]

**Comment by LG27** [comment]
`07-06 15:53:55.116 3062-3062/com.niu.dialogfragment E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.niu.dialogfragment, PID: 3062
                                                                      java.lang.NullPointerException: Attempt to invoke interface method 'void com.niu.dialogfragment.widget.ConfirmDialogFragment$ConfirmDialogListener.onClick(android.content.DialogInterface, int)' on a null object reference
                                                                          at com.niu.dialogfragment.widget.ConfirmDialogFragment$1.onClick(ConfirmDialogFragment.java:72)
                                                                          at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6261)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:803)`
当提示弹出后旋转屏幕，点击事件好使，但当直接点击提示窗按钮时崩溃，error如上

**Comment by LG27** [comment]
不好意思，看提交记录发现已经修复了，[查看](https://github.com/niuxiaowei/DialogFragmentUse/pull/4/commits/257f7bec30f3dd722a8e5ec93ad8e884f2a033ed)
